name: Node
on: [push]

jobs:
  build:
    name: Node
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@master

      - name: Install
        run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: update

      - name: Depcheck
        run: yarn depcheck

      - name: Lint
        run: yarn prettier

      # - name: Doc
      #   run: yarn run doc

      - name: Tests
        run: yarn test

      - name: Build
        run: yarn build

      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
